# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/ytdlp-server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
