# fly.toml app configuration file generated for yt-dlp-api on 2023-05-23T11:25:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yt-dlp-api"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 1024

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  FASTIFY_ADDRESS = "0.0.0.0"
  FASTIFY_LOG_LEVEL = "info"
  FASTIFY_OPTIONS = "true"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"

[metrics]
  port = 9093 # TODO: make this consistent
  path = "/metrics"
