name: flyctl deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref to deploy'
        required: true
        default: 'master'

env:
  python_version: '3.x'
  FORCE_COLOR: 1

concurrency: # prevent concurrent releases
  group: flyctl-deploy
  cancel-in-progress: true

jobs:
  flyctl_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 11.5.2
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ env.python_version }}
        architecture: "x64"
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: pnpm install --frozen-lockfile
    - run: pnpm run deploy -- --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
